a = input ('Digite um algo:')
print ('o tipo primitivo desse valor é' ,type (a))
print ('contém espaços?', a.isspace())
print ('é um numero?' , a.isnumeric())
print ('é alfabetico?' , a.isalpha())
print ('é alfanumérco?' , a.isalnum())
print ('esta maiuscula?' ,a.isupper())
print ('está minuscula?' ,a.islower())
print ('está capitalizada?' , a.istitle())
